### ISSUE TITLE
save-svg-as-png dependency version not fixed to working version

### ISSUE THREAD

**Issue by nwouda** [LINCnil/pia#252] opened 2018-08-06 12:34 UTC
As of release v1.4.3 of save-svg-as-png the `saveSvgAsPng.js` file has moved to the src subfolder. Because of that it became incompatible.

**Comment by kosmas58** [comment] 2018-08-06 18:46
My [development branch of pia](https://github.com/kosmas58/pia) is updated to Angular 6 and uses `angular2-csv 0.29` and `save-svg-as-png 1.4.5`.

**Comment by LaboCNIL** [comment] 2018-08-22 12:09
Same as #254 the issue is fixed on the master branch of pia-back and pia.

**Closed by LaboCNIL** 2018-08-22 12:09 UTC
